baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "arm-design-system-hugo-theme"

enableGitInfo = true

[frontmatter]
    lastmod = [ "lastmod", ":git", "date", "publishDate" ]


[taxonomies]
    skilllevel      = "skilllevels"
    armip           = "armips"
    tool            = "tools"
    software        = "softwares"

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "software"
        weight = 100

    [[related.indices]]
        name = "tools"
        weight = 80
    
    [[related.indices]]
        name = "armips"
        weight = 50