baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "arm-design-system-hugo-theme"

[taxonomies]
    skilllevel      = "skilllevels"
    armip           = "armips"
    toolother      = "toolsother"
    toolArm        = "toolsArm"
    softwareother  = "softwaresother"
    softwareArm    = "softwaresArm"
