baseURL = '/'
languageCode = 'en-us'
title = 'Arm Software Developers'
theme = "arm-design-system-hugo-theme"

enableGitInfo = true

[frontmatter]
    lastmod = [ "lastmod", ":git", "date", "publishDate" ]


[taxonomies]
    skilllevel          = "skilllevels"
    armip               = "armips"
    tool                = "tools"
    software            = "softwares"
    subject             = "subjects"
    developerprogram   = "developerprograms"
    operatingsystem    = "operatingsystems"

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "software"
        weight = 100

    [[related.indices]]
        name = "tools"
        weight = 80
    
    [[related.indices]]
        name = "armips"
        weight = 50