baseURL = '/'
languageCode = 'en-us'
title = 'Arm Software Developers'
theme = "arm-design-system-hugo-theme"

enableGitInfo = true

[deployment]
[[deployment.targets]]
name = "aws"
URL = "s3://armswdev.tk?region=us-east-1"
cloudFrontDistributionID = "E1KJFR5JSKYU64"


[frontmatter]
    lastmod = [ "lastmod", ":git", "date", "publishDate" ]

[markup.goldmark.renderer]
    unsafe = true

[taxonomies]
    skilllevel          = "skilllevels"
    armip               = "armips"
    tool                = "tools"
    software            = "softwares"
    subject             = "subjects"
    developerprogram   = "developerprograms"
    operatingsystem    = "operatingsystems"

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "software"
        weight = 100

    [[related.indices]]
        name = "tools"
        weight = 80
    
    [[related.indices]]
        name = "armips"
        weight = 50

[params]
# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/zachlas/arm-software-developers-ads"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/zachlas/arm-software-developers-ads"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if your GitHub repo does not have "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch= "main"

